### PR TITLE
#184948184 A buyer should be able to search for products

### PR DESCRIPTION
**Pull request by Zeden12**
#### What does this PR do?

this pr is to let a buyer be able to search for a product oh their wish

#### Description of Task to be completed?

so given that we have a lot of products on our website and a buyer wants a specific product due to various reason maybe they recommended the product to him so this PR is to make the search of that product easier

#### How should this be manually tested?

just vist the site `brogrammer's mall` and you can access the search input on the navbar as soon as you get to the landing page and after you get to the landing page you can search any product in any of our seller collection and you will be able to view that product.

#### Any background context you want to provide?

if you click on `view details` button you'll be able to get all details about product on its single page

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184948184

#### Screenshots (if appropriate)
Screen Shot 2023-05-11 at 18 41 19
Screen Shot 2023-05-11 at 18 43 42

#### Questions:
n/a

### CODE REVIEW

**Review by edwinnambaje — APPROVED** [review]

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by INValentin — APPROVED** [review]
LGTM

**Review by Habihirwe — APPROVED** [review]
LGMT

**Review by Habihirwe — APPROVED** [review]
LGMT

**Review by UmuhireJessie — APPROVED** [review]
Good work!

**Pull request merged**
