### PR TITLE
184948159 reset password

### PR DESCRIPTION
**Pull request by bencyubahiro77**
#### What does this PR do?
Reset Password

#### Description of Task to be completed?
the user will be able to reset password when he forgot

#### How should this be manually tested?

- after cloning run `npm install`
- then run `npm start`
- then run in the url `http://localhost:3000/reset-pass`

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2639400/stories/184948159
#### Screenshots (if appropriate)
Screenshot 2023-04-28 at 19 08 59
Success
failed

### CODE REVIEW

**Review by Habihirwe — APPROVED** [review]
well done !

**Review by blackd44 — APPROVED** [review]
Looks Good

**Review by Patienceineza — COMMENTED** [review]
add more screen shot

**Comment by bencyubahiro77** [comment]
> add more screen shot

done

**Review by edwinnambaje — APPROVED** [review]

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
