### PR TITLE
#184948166 view and edit user profile 

### PR DESCRIPTION
**Pull request by Habihirwe**
**What does this PR do?**
Users should be able to view and edit their profiles
 **Description of Task to be completed?**
as the user logged in should be able to see his/ her profile which include Personal Information name, email, gender, birthdate,
preferred language, preferred currency, and where you live, and be able to change them if they want
 **How should this be manually tested?**
this can be tested manually by visiting brogrammersMall app  then login and you should be able to view and edit profile 
 **Any background context you want to provide?**
n/a

 **What are the relevant pivotal tracker/Trello stories?**
https://www.pivotaltracker.com/story/show/184948166
 **Screenshots (if appropriate)**

 **Questions:**
n/a

### CODE REVIEW

**Review by blackd44 — COMMENTED** [review]
Rebase your work
and if possible you can squash your commits

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Resolve the conflicts

**Review by edwinnambaje — COMMENTED** [review]
adding screenshots could also help

**Review by edwinnambaje — CHANGES_REQUESTED** [review]
Screenshot 2023-05-23 at 18 12 34
can you also fix this?

**Review by bencyubahiro77 — APPROVED** [review]

**Review by UmuhireJessie — APPROVED** [review]

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]

**Review by Patienceineza — APPROVED** [review]
LGTM

**Pull request merged**
