### PR TITLE
184948159 reset password

### PR DESCRIPTION
**Pull request by bencyubahiro77**
#### What does this PR do?
User can Reset password
#### Description of Task to be completed?
The user will be able to reset his password in case their forgot it
#### How should this be manually tested?
*    After cloning the repo `run npm install`
*    Then run `npm start`
*    To switch to the reset password page in your browser in the URL write `http://localhost:3000/reset-pass`
*    Then you can reset your password , you will get success toast message to check your email if the entered email is in the DB or get failed message if not found

#### Any background context you want to provide?
n/a

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2639400/stories/184948159

#### Screenshots (if appropriate)
Screenshot 2023-04-24 at 18 53 21

### CODE REVIEW

**Review by INValentin — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]

**Review by edwinnambaje — APPROVED** [review]

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by edwinnambaje — CHANGES_REQUESTED** [review]
Can you remove .env and also add screenshot for tests

**Comment by bencyubahiro77** [comment]
> Can you remove .env and also add screenshot for tests

which .env to remove?  and for test take a look down you will see the test percentage

**Review by edwinnambaje — APPROVED** [review]

**Pull request closed without merging**
