### PR TITLE
#184948175 A buyer should  perform crud operations on  cart

### PR DESCRIPTION
**Pull request by edwinnambaje**
#### What does this PR do?
- A buyer should be able to perform crud operations on cart and also fixed some bugs
#### Description of Task to be completed?
- A buyer should be able to perform crud operations on cart
#### How should this be manually tested?
after cloning this repository
1. add environment variables as are in .env.example
2. run npm install to install all dependencies
3. run npm start and open in it the browser
4. after `login` as a buyer
5. you'll find the `cart icon` button then jump to it to check your cart
6. you can add a product to cart using the cart icon
####  Bugs  fixed
-  added cursor-pointer when hovering on categories
-  position of the toasts should be consistent through out
-  add a label of expiration data field when adding a product
-  price of a product should be reflecting what you have input

#### Any background context you want to provide?
- n/a
#### What are the relevant pivotal tracker/Trello stories?
- [Add To Cart](https://www.pivotaltracker.com/n/projects/2639400/stories/184948175)
- [View Cart](https://www.pivotaltracker.com/n/projects/2639400/stories/184948176)
- [Clear Cart](https://www.pivotaltracker.com/n/projects/2639400/stories/184948177)
- [Update Cart](https://www.pivotaltracker.com/n/projects/2639400/stories/184948178)

#### Screenshots (if appropriate)
Screenshot 2023-05-19 at 13 30 40
Screenshot 2023-05-19 at 13 30 47
Screenshot 2023-05-19 at 13 30 59
Screenshot 2023-05-05 at 12 29 11
Screenshot 2023-05-19 at 13 25 13
Screenshot 2023-05-19 at 13 25 22
/56297754/236435167-43585a67-de57-4b6f-beaa-ea32ccd865f4.png">
Screenshot 2023-05-19 at 15 25 35

### CODE REVIEW

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Update PR description

**Comment by edwinnambaje** [comment]
> Update PR description

done

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
