### PR TITLE
#184948180 user's orders CRUD 

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
- use CRUD for user orders
- bug fix
#### Description of Task to be completed?
- This feature should allow a user to proceed to the next step which is completing the payment process.
The process, includes validating and processing the order, updating inventory, and redirecting the customer to the payment portal.
- fixed css bug and remove bootstrap

#### How should this be manually tested?
after cloning this repository
1. add environment variables as are in .env.example
2. run npm install to install all dependencies
3. run npm start and open in it the browser
4. after `login` as seller
5. you'll find the `add product` button then jump to it.
#### Any background context you want to provide?
- stripe
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/story/show/184948180
#### Screenshots (if appropriate)
Screen Shot 2023-05-22 at 17 47 45
Screen Shot 2023-05-22 at 18 26 02
Screen Shot 2023-05-22 at 18 26 24
Screen Shot 2023-05-22 at 18 27 15
Screen Shot 2023-05-22 at 18 28 01

#### Questions:
n/a

### CODE REVIEW

**Review by edwinnambaje — COMMENTED** [review]
change PR title and you are good to go

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]

**Review by INValentin — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
