### PR TITLE
#184948149 Setup react router

### PR DESCRIPTION
**Pull request by edwinnambaje**
#### What does this PR do?
- Setup react router

#### Description of Task to be completed?
- Setup react router dom

#### How should this be manually tested?
after cloning this repository
1.  add environment variables as are in `.env.example`
2.  run `npm install` to install all dependencies
3. run `npm start` and open in it the browser
4. Navigate to login using `http://localhost:3000/login`

#### Any background context you want to provide?
dependencies
- React-router-dom

#### What are the relevant pivotal tracker/Trello stories?
- [react-router-dom](https://www.pivotaltracker.com/n/projects/2639400/stories/184948149)

#### Screenshots (if appropriate)
Screenshot 2023-04-18 at 18 09 45
Screenshot 2023-04-18 at 18 09 51
Screenshot 2023-04-19 at 00 33 22

### CODE REVIEW

**Review by Habihirwe — APPROVED** [review]
well done

**Review by INValentin — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]

**Review by blackd44 — APPROVED** [review]
Looks Good

**Review by UmuhireJessie — COMMENTED** [review]
Resolve the conflicts

**Comment by edwinnambaje** [comment]
> Resolve the conflicts

done

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
